### ISSUE TITLE
Add a GUI for YouTube Manager using HTML, CSS, and JavaScript

### ISSUE THREAD

**Issue by saumyaranjan2003** [saumyaranjan2003/YouTube_Manager_App#1]
The current implementation of the YouTube Manager application is a simple Python application that allows users to manage their favorite YouTube videos through the command line. To enhance user experience and make the application more accessible, we propose to develop a graphical user interface (GUI) using HTML, CSS, and JavaScript.

**Comment by SaumyaRanjan-Dev** [comment]
i will do it

**Comment by rnihesh** [comment]
I'll do it
